{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "nexus.name" . }}
  {{- if .Values.namespace.enabled }}
  namespace: {{ .Values.namespace.name }}
  {{- else }}
  namespace: default
  {{- end }}
  labels:
{{ include "nexus.labels" . | indent 4 }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}

spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .name }}
    http:
      paths:
      - path: /
        backend:
          serviceName: nexus-service-lb
          servicePort: nexus-service

  - host: {{ .name2 }}
    http:
      paths:
      - path: /
        backend:
          serviceName: nexus-service-lb
          servicePort: 1111
  {{- end}}
  {{- range .Values.ingress.hosts }}
  {{- if .tls }}
  tls:
  {{- end }}
  {{- end }}
  {{- range .Values.ingress.hosts }}
  {{- if .tls }}
  - hosts:
  {{- if .tlsHosts }}
  {{- range $host := .tlsHosts }}
    - {{ $host }}
  {{- end }}
  {{- else }}
    - {{ .name }}
  {{- end }}
    # secretName: {{ .tlsSecret }}
  {{- end }}
  {{- end }}
{{- end }}