kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.persistence.storageClass }}
provisioner: kubernetes.io/aws-ebs
parameters:
  type: {{ .Values.persistence.storageType }}
reclaimPolicy: Delete
mountOptions:
  - debug