apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  {{- if .Values.namespace.enabled }}
  namespace: {{ .Values.namespace.name }}
  {{- else }}
  namespace: default
  {{- end }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: {{ .Values.appName }}
  type: {{ .Values.serviceType }}
