{{- if .Values.storageClass.enabled }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.storageClass.storageClassName }}
provisioner: kubernetes.io/aws-ebs
parameters:
  type: {{ .Values.storageClass.storageType }}
reclaimPolicy: Delete
mountOptions:
  - debug
{{- end }}
